spring:
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
  datasource:
    url: jdbc:h2:mem:bankapp
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

active-mq:
  broker-url: 'failover://tcp://localhost:61616'
  topic: 'message'
